platform :ios, '7.0'
pod 'CRToast', :git => 'https://github.com/cruffenach/CRToast'
pod 'FontAwesomeIconFactory'
pod 'RestKit', '~> 0.22.0'
pod 'PDKeychainBindingsController', '~> 0.0.1'
pod 'MCSwipeTableViewCell', '~> 2.1.0'
pod 'VTAcknowledgementsViewController'
pod 'NSDate+TimeAgo'
pod 'SDWebImage'
pod 'NSString+Emoji'
