platform :ios, '7.0'
pod 'CRToast', :git => 'https://github.com/cruffenach/CRToast'
pod 'FontAwesomeIconFactory'
pod 'RestKit', '~> 0.23.1'
pod 'PDKeychainBindingsController', '~> 0.0.1'
pod 'MCSwipeTableViewCell', '~> 2.1.0'
pod 'VTAcknowledgementsViewController'
pod 'SDWebImage'
pod 'NSDate+TimeAgo'
pod 'NSString+Emoji'
pod 'HockeyKit', '~> 2.0.7'
pod 'uservoice-iphone-sdk'
pod 'XLForm', '~> 2.0'
pod 'FLEX'
