platform :ios, '7.0'
pod 'CRToast', :git => 'https://github.com/cruffenach/CRToast'
pod 'FontAwesomeIconFactory'
pod 'RestKit', '~> 0.24.1'
pod 'RestKit/Testing'
pod 'PDKeychainBindingsController', '~> 0.0.1'
pod 'MCSwipeTableViewCell', '~> 2.1.0'
pod 'VTAcknowledgementsViewController'
pod 'SDWebImage'
pod 'DateTools'
pod 'NSString+Emoji'
pod 'XLForm'
pod 'FLEX'
pod 'pop'
pod 'OHHTTPStubs'
pod 'EAIntroView', '~> 2.6.0'
pod 'DTCoreText'
pod 'CargoBay', :git => 'https://github.com/segiddins/CargoBay.git', :branch => 'v1'
pod 'MRProgress'
