//
// Copyright 2011-2014 NimbusKit
//
// Autogenerated by flex using Jeff Verkoeyen's Markdown grammar
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#define YY_NO_INPUT

#include "MarkdownTokens.h"

#line 3 "lex.markdown.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE markdownrestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via markdownrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void markdownrestart (FILE *input_file ,yyscan_t yyscanner );
void markdown_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE markdown_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void markdown_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void markdown_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void markdownpush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void markdownpop_buffer_state (yyscan_t yyscanner );

static void markdownensure_buffer_stack (yyscan_t yyscanner );
static void markdown_load_buffer_state (yyscan_t yyscanner );
static void markdown_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER markdown_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE markdown_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE markdown_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE markdown_scan_bytes (yyconst char *bytes,yy_size_t len ,yyscan_t yyscanner );

void *markdownalloc (yy_size_t ,yyscan_t yyscanner );
void *markdownrealloc (void *,yy_size_t ,yyscan_t yyscanner );
void markdownfree (void * ,yyscan_t yyscanner );

#define yy_new_buffer markdown_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        markdownensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            markdown_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        markdownensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            markdown_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 15
#define YY_END_OF_BUFFER 16
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[311] =
    {   0,
        0,    0,   16,   14,   13,   13,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,    6,   14,    0,    0,
       12,    0,    0,    0,    1,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    1,    0,    5,    0,    6,
        6,   10,    0,    0,   12,   11,    0,    1,    0,    1,
        0,    0,    0,    0,    0,    8,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    6,    7,    7,    0,    0,    0,    0,    0,    0,
        2,    8,    0,    8,    8,    0,    8,    8,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    7,

        0,    0,    0,    0,    0,    0,    2,    4,    6,    2,
        2,    7,    0,    0,    0,    0,    0,    8,    0,    8,
        8,    8,    0,    8,    8,    8,    8,    0,    0,    0,
        0,    0,    8,    0,    0,    0,    0,    7,    0,    0,
        0,    0,    0,    6,    0,    7,    3,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    0,    8,
        8,    0,    0,    0,    9,    8,    8,    0,    0,    7,
        0,    6,    3,    8,    8,    8,    8,    0,    8,    8,
        8,    8,    8,    0,    8,    8,    8,    8,    8,    0,
        8,    8,    8,    8,    0,    0,    8,    8,    8,    8,

        8,    8,    8,    8,    8,    8,    8,    8,    0,    8,
        8,    8,    8,    8,    8,    0,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    0,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    0,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,

        8,    8,    8,    8,    8,    8,    8,    8,    8,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    6,    7,    6,    6,    6,    6,    8,
        9,   10,    6,    6,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,    6,    6,
       16,    6,    6,    6,   14,   14,   14,   14,   14,   17,
       18,   19,   18,   18,   18,   18,   18,   18,   18,   20,
       18,   18,   21,   22,   18,   18,   18,   18,   18,   18,
       23,   24,   25,    6,   26,   27,   14,   14,   14,   14,

       14,   28,   18,   29,   18,   18,   18,   18,   18,   18,
       18,   30,   18,   18,   31,   32,   18,   18,   18,   18,
       18,   18,    6,    6,    6,   33,    1,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,

       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34
    } ;

static yyconst flex_int32_t yy_meta[35] =
    {   0,
        1,    1,    1,    1,    2,    2,    2,    2,    2,    2,
        3,    4,    5,    3,    2,    6,    3,    3,    3,    3,
        3,    3,    2,    3,    2,    2,    2,    3,    3,    3,
        3,    3,    2,    3
    } ;

static yyconst flex_int16_t yy_base[355] =
    {   0,
        0,   28,  587,  583,  582,  576,   33,   34,   42,   18,
       19,  569,   76,   39,   40,   49,   78,   44,  558,   72,
      557,   43,   65,   76,   81,  547,  102,  136,   77,   86,
       44,    0,  163,   91,   84,   99,  100,  108,   96,  549,
      138,  538,  137,   98,  531,  135,  149,  529,  521, 1621,
      159,  153,  162,  171,  181,  205,  239,  513,  266,  173,
      159,  241,  234,  130,  497,  248,  156,  236,  157,  154,
      173,  183, 1621,  512,  204,  495,  489,  274,  218,  244,
      228,  284,  318,  484,  336,  370,    0,  397,  275,  265,
       93,  100,  312,  205,  489,  462,  265,  283,  309,  452,

      158,  451,  314,  408,  194,  318,  262,  306,  254,  428,
     1621,  408,  328,  405,  385,  366,  338,    0,  425,    0,
      452,    0,  480,  374,  507,  367,  335,  338,  375,  260,
      372,  385,  392,  379,  374,  534,  392,  335,  325,  319,
      419,  316,  333,  410,  300,  297,  289,    0,  561,  408,
      419,    0,  588,  432,  423,  447,  399,  277,  424,  432,
      448,  448,  457,  616,  464,    0,  649,  473,  474,  249,
      246,  245, 1621,  482,  486,  229,  459,  490,  499,  504,
      512,  516,  455,  529,  205,  676,  539,  531,  703,  541,
      721,  745,  779,  554,  556,  560,  566,  538,  806,  581,

      193,  582,  583,  565,  833,  587,  641,  642,  643,  181,
      851,  885,    0,  912,  647,  648,  668,  669,  670,  675,
      685,  695,  701,  708,  716,  930,  954,  988,  143, 1015,
      720,  744,  771,  772,  773,  777,  778,  798,  799,  800,
      804, 1033, 1067,  131, 1085, 1119,    0, 1146,  805,  825,
      826, 1173,  831,  838,  846,  850,  877,  878,    0, 1189,
        0, 1216,    0, 1244,  116, 1271,  879,  883,  884,  916,
      908,  910,  914, 1298,    0, 1313,  918,    0, 1340,  949,
      980,  981,  982,  986, 1367,  987, 1007, 1008, 1009, 1014,
     1032, 1059, 1060, 1061, 1065, 1066, 1083, 1084, 1111, 1112,

     1113, 1117, 1118, 1138, 1139, 1140, 1144, 1145, 1168, 1621,
     1383, 1389, 1395, 1401, 1407, 1413, 1419, 1425, 1431, 1437,
     1443, 1449, 1455, 1461, 1467, 1473, 1477, 1483, 1489, 1495,
     1501, 1507, 1513,   55, 1518, 1524, 1530, 1536, 1540,   54,
     1545, 1549, 1553, 1557, 1562, 1567, 1572, 1578, 1584, 1590,
     1596, 1602, 1608, 1614
    } ;

static yyconst flex_int16_t yy_def[355] =
    {   0,
      310,    1,  310,  311,  311,  310,  311,  312,  311,    9,
        9,  313,  314,  315,  316,  311,  317,    9,  311,  310,
      310,  311,  312,  318,  319,    9,  311,  320,    9,    9,
      313,    9,    9,  315,  321,  322,  316,  316,  323,  317,
      317,  311,    9,  310,  310,  310,  311,  311,  318,  310,
      318,  319,  324,  325,   27,    9,  326,    9,    9,    9,
        9,  313,  327,   33,  321,  321,  322,  328,  329,  323,
      323,  317,  310,  318,  311,  324,  310,  324,  325,  330,
      311,   56,  331,   56,   82,  332,   56,   56,  327,   59,
      311,    9,    9,  333,   89,  334,   89,  335,   33,  321,

      311,  328,  328,  310,  329,  336,  311,  323,  317,  311,
      310,  324,  311,  330,  310,  330,  311,   82,  337,   82,
       82,   85,  338,   56,   56,  339,   88,  340,   59,  311,
      333,  333,  339,  341,   89,   89,   33,  328,  311,  336,
      336,  310,  311,  317,  310,  330,  311,   82,   82,  342,
      121,   85,   85,  133,  125,  133,  343,  133,  344,   88,
      342,  345,   59,  310,  333,  133,  133,  136,   33,  336,
      310,  317,  310,  342,  149,  174,  174,  346,  121,  343,
      153,  125,  343,  347,  133,  133,   88,  174,  174,   59,
      164,  164,  348,  167,  136,   33,  149,  174,  189,  121,

      180,  153,  125,  180,  180,  186,   88,  189,   59,  192,
      164,  349,  192,  192,  167,  136,  149,  199,  121,  153,
      125,  205,  186,   88,  189,  164,  192,  350,  192,  192,
      214,  167,  136,  149,  199,  121,  153,  125,  205,  186,
      189,  227,  351,  227,  242,  352,  227,  227,  230,  214,
      167,   89,  149,  199,  153,  205,  186,  189,  242,  353,
      242,  242,  245,  354,  227,  227,  248,  230,  214,  133,
      199,  205,  186,  174,  242,  242,  262,  245,  245,  266,
      248,  230,  214,  199,  180,  276,  262,  279,  266,  248,
      230,  214,  276,  262,  279,  266,  248,  230,  276,  262,

      279,  266,  248,  276,  262,  279,  266,  276,  279,    0,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310
    } ;

static yyconst flex_int16_t yy_nxt[1656] =
    {   0,
        4,    5,    6,    4,    7,    4,    4,    4,    4,    8,
        9,    4,    4,    9,    4,    4,   10,    9,   11,    9,
        9,    9,   12,   13,    4,   14,   15,   10,   11,    9,
        9,    9,   16,    9,   17,   20,   24,   22,   18,   29,
       30,   35,   20,   25,   20,   46,   20,   47,   42,   29,
       30,   20,   26,   27,   43,   26,  161,  133,   26,   26,
       26,   26,   26,   26,   36,   28,   38,   24,   62,   26,
       26,   26,   26,   26,   48,   26,   19,   19,   20,   19,
       20,   39,   44,   53,   41,   50,   51,   44,   55,   33,
       54,   51,   33,   35,   66,   20,   60,   55,   20,   66,

       73,   68,   20,   33,   20,  130,   60,   61,   44,   50,
       20,   55,   56,   44,   91,   56,   48,   61,   56,   56,
       56,   56,   56,   56,   69,   57,   38,  226,   71,   56,
       56,   56,   56,   56,   38,   56,   19,   19,   20,   19,
       20,   42,  226,   99,   72,   44,   99,   43,   55,   59,
       44,   46,   59,   47,  226,   53,   20,   99,   68,  106,
       20,   74,   75,   59,   32,   63,   32,   32,   50,   51,
       55,   77,   78,   80,   51,   20,   64,   78,   93,   64,
       81,  101,  107,  110,   55,   20,   71,   91,   93,  109,
       64,   82,  226,   92,   82,   73,  106,   82,   82,   82,

       82,   82,   82,   92,   83,  108,   20,   20,   82,   82,
       82,   82,   82,  110,   82,   84,  128,   85,   84,  139,
       80,   84,   84,   84,   84,   84,   84,  113,   86,  132,
       20,   73,   84,   84,   84,   84,   84,  117,   84,   19,
       19,   20,   19,   20,   95,   96,  103,   20,   94,   44,
      100,  103,   88,  115,  116,   88,   20,   98,   66,  116,
      144,  104,   20,   66,   20,   62,   88,   58,   89,   58,
       58,  173,  164,   50,  142,   97,  112,   55,  129,   90,
      310,  129,   90,   77,   78,   95,  128,  143,  128,   78,
       44,   20,  129,   90,  118,   19,  136,  118,   98,  136,

      118,  118,  118,  118,  118,  118,  115,  119,   20,  173,
      136,  118,  118,  118,  118,  118,  138,  118,   19,   19,
       20,   19,  137,   55,  103,  137,   91,   20,  141,  103,
       20,  121,   92,  141,  121,   20,  137,  117,  108,  104,
       20,  171,   92,  142,  142,  121,  122,  147,  160,  122,
      143,  160,  122,  122,  122,  122,  122,  122,  147,  123,
      104,  162,  160,  122,  122,  122,  122,  122,  146,  122,
       19,   19,   20,   19,   20,  115,  116,  156,   96,  157,
      165,  116,   44,  125,   97,   55,  125,   20,  163,  310,
      159,  163,  167,  165,  145,  167,  132,  125,   87,  126,

       87,   87,  163,   96,  157,  169,  167,  310,  169,  132,
      127,  157,   20,  127,  115,  159,  172,   77,  176,  169,
      157,  170,  184,   44,  127,   19,   19,   20,   19,  141,
       20,  178,  179,  111,  141,  179,  182,  186,  149,  182,
      186,  149,  156,  128,  142,  187,  179,   44,  187,   73,
      182,  186,  149,  120,  150,  120,  120,  156,  128,  187,
      157,  189,   44,  310,  189,  151,   20,  157,  151,  177,
      190,  178,  165,  190,  310,  189,  104,   50,  184,  151,
       19,   19,   20,   19,  190,  134,  195,  196,  132,  195,
      196,   73,  176,  153,  157,   55,  153,   44,  111,  197,

      195,  196,  197,  199,   77,  178,  199,  153,  124,  154,
      124,  124,  200,  197,  201,  200,  157,  199,   55,   44,
      155,   50,   50,  155,   55,  202,  200,  184,  202,  203,
       50,   20,  203,   45,  155,  135,  135,  135,  135,  202,
       20,  177,  205,  203,   97,  205,  310,  168,  177,  310,
      168,   20,  207,  310,  209,  207,  205,  209,   55,   45,
       20,  168,  148,  174,  148,  148,  207,  215,  209,  216,
      215,   20,  216,   26,  175,  183,   26,  175,   21,  217,
      310,  215,  217,  216,   20,   20,  310,   26,  175,  152,
      180,  152,  152,  217,  219,  220,  221,  219,  220,  221,

      223,  181,  310,  223,  181,  310,  310,  310,  219,  220,
      221,  310,  310,  310,  223,  181,  191,  191,   20,  191,
       19,  191,  191,  191,  191,  191,  192,  191,  191,  192,
      191,  191,  192,  192,  192,  192,  192,  192,  191,  193,
      191,  191,  191,  192,  192,  192,  192,  192,  191,  192,
      166,  166,  166,  166,  224,  225,   26,  224,  225,   26,
      232,  233,  194,  232,  233,  194,  310,  310,  224,  225,
       26,  310,  310,  310,  232,  233,  194,  185,  185,  185,
      185,  234,  235,  236,  234,  235,  236,  128,  237,  206,
      310,  237,  206,  310,  310,  234,  235,  236,  238,  310,

      310,  238,  237,  206,  188,  188,  188,  188,  239,  310,
      310,  239,  238,  177,  240,  310,  208,  240,  310,  208,
      310,   84,  239,  310,   84,  310,  310,  310,  240,  241,
      208,  191,  241,  250,  191,   84,  250,  191,  191,  191,
      191,  191,  191,  241,  191,  310,  310,  250,  191,  191,
      191,  191,  191,  310,  191,  210,  211,  251,  210,  310,
      251,  210,  210,  210,  210,  210,  210,  310,  212,  310,
      310,  251,  210,  210,  210,  210,  210,  310,  210,  191,
      191,   20,  191,   32,  252,  253,  254,  252,  253,  254,
      118,  255,  214,  118,  255,  214,  310,  310,  252,  253,

      254,  310,  310,  310,  118,  255,  214,  198,  198,  198,
      198,   84,  256,  257,   84,  256,  257,  258,  268,  218,
      258,  268,  218,  310,  310,   84,  256,  257,  310,  310,
      310,  258,  268,  218,  204,  204,  204,  204,  269,  270,
      310,  269,  270,  183,  118,  310,  222,  118,  310,  222,
      310,  271,  269,  270,  271,  310,  310,  310,  118,  122,
      222,  227,  122,  272,  227,  271,  272,  227,  227,  227,
      227,  227,  227,  122,  228,  310,  310,  272,  227,  227,
      227,  227,  227,  310,  227,  191,  191,   20,  191,   58,
      273,  274,  281,  273,  274,  281,  282,  283,  230,  282,

      283,  230,  310,  310,  273,  274,  281,  310,  310,  310,
      282,  283,  230,  213,   63,  213,   32,  166,  166,  166,
      166,  284,  310,  285,  284,  231,  285,  158,  231,  310,
      158,  287,  310,  310,  287,  284,  310,  285,  310,  231,
      242,  158,  310,  242,  310,  287,  242,  242,  242,  242,
      242,  242,  310,  243,  310,  310,  310,  242,  242,  242,
      242,  242,  289,  242,  244,  289,  245,  244,  310,  310,
      244,  244,  244,  244,  244,  244,  289,  246,  310,  310,
      310,  244,  244,  244,  244,  244,  310,  244,  191,  191,
       20,  191,   87,  290,  291,  292,  290,  291,  292,  177,

      293,  248,  177,  293,  248,  310,  310,  290,  291,  292,
      310,  310,  310,  177,  293,  248,  229,   89,  229,   58,
      294,  295,  296,  294,  295,  296,  226,  297,  249,  310,
      297,  249,  310,  310,  294,  295,  296,  310,  310,  310,
      310,  297,  249,  259,  191,  298,  259,  310,  298,  259,
      259,  259,  259,  259,  259,  310,  260,  310,  310,  298,
      259,  259,  259,  259,  259,  310,  259,  191,  191,   20,
      191,  120,  210,  299,  300,  210,  299,  300,  301,  302,
      262,  301,  302,  262,  310,  310,  210,  299,  300,  310,
      310,  310,  301,  302,  262,  263,  303,  210,  263,  303,

      210,  263,  263,  263,  263,  263,  263,  310,  264,  310,
      303,  210,  263,  263,  263,  263,  263,  310,  263,  191,
      191,   20,  191,  124,  304,  305,  306,  304,  305,  306,
      307,  244,  266,  307,  244,  266,  310,  310,  304,  305,
      306,  310,  310,  310,  307,  244,  266,  247,  126,  247,
       87,  308,  259,  309,  308,  259,  309,  244,  259,  267,
      244,  259,  267,  310,  310,  308,  259,  309,  310,  310,
      310,  244,  259,  267,  135,  135,  135,  135,  310,  310,
      310,  263,  310,   97,  263,  310,  310,  310,  310,  191,
      191,   20,  191,  148,  310,  263,  310,  310,  310,  310,

      310,  310,  276,  310,  310,  276,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  276,  261,  150,  261,
      120,  310,  310,  310,  310,  310,  310,  310,  310,  277,
      310,  310,  277,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  277,  191,  191,   20,  191,  152,  310,
      310,  310,  310,  310,  310,  310,  310,  279,  310,  310,
      279,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  279,  265,  154,  265,  124,  310,  310,  310,  310,
      310,  310,  226,  310,  280,  310,  310,  280,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  280,  188,

      188,  188,  188,  310,  310,  310,  310,  310,  177,  310,
      310,  310,  310,  310,  275,  174,  275,  148,  310,  310,
      310,  310,  310,  310,  310,  310,  286,  310,  310,  286,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      286,  278,  180,  278,  152,  310,  310,  310,  310,  310,
      310,  310,  310,  288,  310,  310,  288,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  288,  204,  204,
      204,  204,  310,  310,  310,  310,  310,  183,  310,  310,
      310,  310,  310,   19,   19,   19,   19,   19,   19,   23,
       23,   23,   23,   23,   23,   31,   31,   31,   31,   31,

       31,   32,   32,   32,   32,   32,   32,   34,   34,   34,
       34,   34,   34,   37,   37,   37,   37,   37,   37,   40,
       40,   40,   40,   40,   40,   49,   49,   49,   49,   49,
       49,   52,   52,   52,   52,   52,   52,   58,   58,   58,
       58,   58,   58,   65,   65,   65,   65,   65,   65,   67,
       67,   67,   67,   67,   67,   70,   70,   70,   70,   70,
       70,   76,   76,   76,   76,   76,   76,   79,   79,   79,
       79,   79,   79,   87,   87,   87,   87,   87,   87,   97,
       97,  310,   97,  102,  102,  102,  102,  102,  102,  105,
      105,  105,  105,  105,  105,  114,  114,  114,  114,  114,

      114,  120,  120,  120,  120,  120,  120,  124,  124,  124,
      124,  124,  124,  131,  131,  131,  131,  131,  131,  135,
      135,  135,  135,  135,  140,  140,  140,  140,  140,  140,
      148,  148,  148,  148,  148,  148,  152,  152,  152,  152,
      152,  152,  158,  158,  158,  158,  166,  166,  166,  166,
      166,  177,  310,  177,  177,  183,  310,  183,  185,  185,
      185,  185,  185,  188,  188,  188,  188,  188,  198,  198,
      198,  198,  198,  204,  204,  204,  204,  204,  213,  213,
      213,  213,  213,  213,  229,  229,  229,  229,  229,  229,
      247,  247,  247,  247,  247,  247,  261,  261,  261,  261,

      261,  261,  265,  265,  265,  265,  265,  265,  275,  275,
      275,  275,  275,  275,  278,  278,  278,  278,  278,  278,
        3,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310
    } ;

static yyconst flex_int16_t yy_chk[1656] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,    7,    8,    7,    2,   10,
       11,   14,   15,    8,    9,   22,   31,   22,   18,   10,
       11,   16,    9,    9,   18,    9,  340,  334,    9,    9,
        9,    9,    9,    9,   14,    9,   15,   23,   31,    9,
        9,    9,    9,    9,   23,    9,   13,   13,   13,   13,
       17,   16,   20,   25,   17,   24,   24,   20,   29,   13,
       25,   24,   13,   34,   35,   91,   29,   30,   39,   35,

       44,   36,   37,   13,   27,   91,   29,   30,   44,   35,
       38,   92,   27,   44,   92,   27,   34,   30,   27,   27,
       27,   27,   27,   27,   36,   27,   37,  265,   39,   27,
       27,   27,   27,   27,   38,   27,   28,   28,   28,   28,
       41,   43,  244,   64,   41,   46,   64,   43,   43,   28,
       46,   47,   28,   47,  229,   52,   70,   64,   67,   69,
      101,   51,   52,   28,   33,   33,   33,   33,   51,   51,
       61,   53,   53,   54,   51,   71,   33,   53,   61,   33,
       54,   67,   69,  101,   60,   72,   70,   60,   61,   72,
       33,   55,  210,   60,   55,  201,  105,   55,   55,   55,

       55,   55,   55,   60,   55,   71,   75,   94,   55,   55,
       55,   55,   55,   75,   55,   56,  185,   56,   56,  105,
       79,   56,   56,   56,   56,   56,   56,   79,   56,   94,
       81,  176,   56,   56,   56,   56,   56,   81,   56,   57,
       57,   57,   57,   62,   63,   63,   68,  172,   62,   63,
       66,   68,   57,   80,   80,   57,  109,   63,   66,   80,
      109,   68,  130,   66,  107,   62,   57,   59,   59,   59,
       59,  171,  130,   66,  170,   97,   78,   59,   90,   59,
       97,   90,   59,   78,   78,   89,   89,  107,  158,   78,
       89,  147,   90,   59,   82,   82,   98,   82,   89,   98,

       82,   82,   82,   82,   82,   82,  146,   82,  108,  145,
       98,   82,   82,   82,   82,   82,  103,   82,   83,   83,
       83,   83,   99,   93,  103,   99,   93,  139,  106,  103,
      113,   83,   93,  106,   83,  143,   99,  113,  108,  103,
      117,  142,   93,  106,  140,   83,   85,  117,  127,   85,
      139,  127,   85,   85,   85,   85,   85,   85,  143,   85,
      138,  128,  127,   85,   85,   85,   85,   85,  116,   85,
       86,   86,   86,   86,  131,  116,  116,  126,  126,  126,
      131,  116,  126,   86,  135,  124,   86,  132,  129,  135,
      126,  129,  134,  132,  115,  134,  131,   86,   88,   88,

       88,   88,  129,  133,  133,  137,  134,  133,  137,  132,
       88,  157,  144,   88,  114,  133,  144,  112,  150,  137,
      150,  141,  157,  150,   88,  119,  119,  119,  119,  141,
      110,  150,  151,  104,  141,  151,  155,  159,  119,  155,
      159,  119,  154,  154,  141,  160,  151,  154,  160,  156,
      155,  159,  119,  121,  121,  121,  121,  156,  156,  160,
      161,  162,  156,  161,  162,  121,  165,  183,  121,  177,
      163,  161,  165,  163,  177,  162,  102,  100,  183,  121,
      123,  123,  123,  123,  163,   96,  168,  169,  165,  168,
      169,   95,  174,  123,  174,   84,  123,  174,   77,  175,

      168,  169,  175,  178,   76,  174,  178,  123,  125,  125,
      125,  125,  179,  175,  180,  179,  180,  178,  125,  180,
      125,   74,   65,  125,   58,  181,  179,  180,  181,  182,
       49,   48,  182,   45,  125,  136,  136,  136,  136,  181,
       42,  188,  184,  182,  136,  184,  188,  136,  198,  136,
      136,   40,  187,  198,  190,  187,  184,  190,   26,   21,
       19,  136,  149,  149,  149,  149,  187,  194,  190,  195,
      194,   12,  195,  196,  149,  204,  196,  149,    6,  197,
      204,  194,  197,  195,    5,    4,    3,  196,  149,  153,
      153,  153,  153,  197,  200,  202,  203,  200,  202,  203,

      206,  153,    0,  206,  153,    0,    0,    0,  200,  202,
      203,    0,    0,    0,  206,  153,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      167,  167,  167,  167,  207,  208,  209,  207,  208,  209,
      215,  216,  167,  215,  216,  167,    0,    0,  207,  208,
      209,    0,    0,    0,  215,  216,  167,  186,  186,  186,
      186,  217,  218,  219,  217,  218,  219,  186,  220,  186,
        0,  220,  186,    0,    0,  217,  218,  219,  221,    0,

        0,  221,  220,  186,  189,  189,  189,  189,  222,    0,
        0,  222,  221,  189,  223,    0,  189,  223,  189,  189,
        0,  224,  222,    0,  224,    0,    0,    0,  223,  225,
      189,  191,  225,  231,  191,  224,  231,  191,  191,  191,
      191,  191,  191,  225,  191,    0,    0,  231,  191,  191,
      191,  191,  191,    0,  191,  192,  192,  232,  192,    0,
      232,  192,  192,  192,  192,  192,  192,    0,  192,    0,
        0,  232,  192,  192,  192,  192,  192,    0,  192,  193,
      193,  193,  193,  193,  233,  234,  235,  233,  234,  235,
      236,  237,  193,  236,  237,  193,    0,    0,  233,  234,

      235,    0,    0,    0,  236,  237,  193,  199,  199,  199,
      199,  238,  239,  240,  238,  239,  240,  241,  249,  199,
      241,  249,  199,    0,    0,  238,  239,  240,    0,    0,
        0,  241,  249,  199,  205,  205,  205,  205,  250,  251,
        0,  250,  251,  205,  253,    0,  205,  253,  205,  205,
        0,  254,  250,  251,  254,    0,    0,    0,  253,  255,
      205,  211,  255,  256,  211,  254,  256,  211,  211,  211,
      211,  211,  211,  255,  211,    0,    0,  256,  211,  211,
      211,  211,  211,    0,  211,  212,  212,  212,  212,  212,
      257,  258,  267,  257,  258,  267,  268,  269,  212,  268,

      269,  212,    0,    0,  257,  258,  267,    0,    0,    0,
      268,  269,  212,  214,  214,  214,  214,  270,  270,  270,
      270,  271,    0,  272,  271,  214,  272,  273,  214,    0,
      273,  277,    0,    0,  277,  271,    0,  272,    0,  214,
      226,  273,    0,  226,    0,  277,  226,  226,  226,  226,
      226,  226,    0,  226,    0,    0,    0,  226,  226,  226,
      226,  226,  280,  226,  227,  280,  227,  227,    0,    0,
      227,  227,  227,  227,  227,  227,  280,  227,    0,    0,
        0,  227,  227,  227,  227,  227,    0,  227,  228,  228,
      228,  228,  228,  281,  282,  283,  281,  282,  283,  284,

      286,  228,  284,  286,  228,    0,    0,  281,  282,  283,
        0,    0,    0,  284,  286,  228,  230,  230,  230,  230,
      287,  288,  289,  287,  288,  289,  230,  290,  230,    0,
      290,  230,    0,    0,  287,  288,  289,    0,    0,    0,
        0,  290,  230,  242,  242,  291,  242,    0,  291,  242,
      242,  242,  242,  242,  242,    0,  242,    0,    0,  291,
      242,  242,  242,  242,  242,    0,  242,  243,  243,  243,
      243,  243,  292,  293,  294,  292,  293,  294,  295,  296,
      243,  295,  296,  243,    0,    0,  292,  293,  294,    0,
        0,    0,  295,  296,  243,  245,  297,  298,  245,  297,

      298,  245,  245,  245,  245,  245,  245,    0,  245,    0,
      297,  298,  245,  245,  245,  245,  245,    0,  245,  246,
      246,  246,  246,  246,  299,  300,  301,  299,  300,  301,
      302,  303,  246,  302,  303,  246,    0,    0,  299,  300,
      301,    0,    0,    0,  302,  303,  246,  248,  248,  248,
      248,  304,  305,  306,  304,  305,  306,  307,  308,  248,
      307,  308,  248,    0,    0,  304,  305,  306,    0,    0,
        0,  307,  308,  248,  252,  252,  252,  252,    0,    0,
        0,  309,    0,  252,  309,    0,    0,    0,  252,  260,
      260,  260,  260,  260,    0,  309,    0,    0,    0,    0,

        0,    0,  260,    0,    0,  260,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  260,  262,  262,  262,
      262,    0,    0,    0,    0,    0,    0,    0,    0,  262,
        0,    0,  262,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  262,  264,  264,  264,  264,  264,    0,
        0,    0,    0,    0,    0,    0,    0,  264,    0,    0,
      264,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  264,  266,  266,  266,  266,    0,    0,    0,    0,
        0,    0,  266,    0,  266,    0,    0,  266,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  266,  274,

      274,  274,  274,    0,    0,    0,    0,    0,  274,    0,
        0,    0,    0,  274,  276,  276,  276,  276,    0,    0,
        0,    0,    0,    0,    0,    0,  276,    0,    0,  276,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      276,  279,  279,  279,  279,    0,    0,    0,    0,    0,
        0,    0,    0,  279,    0,    0,  279,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  279,  285,  285,
      285,  285,    0,    0,    0,    0,    0,  285,    0,    0,
        0,    0,  285,  311,  311,  311,  311,  311,  311,  312,
      312,  312,  312,  312,  312,  313,  313,  313,  313,  313,

      313,  314,  314,  314,  314,  314,  314,  315,  315,  315,
      315,  315,  315,  316,  316,  316,  316,  316,  316,  317,
      317,  317,  317,  317,  317,  318,  318,  318,  318,  318,
      318,  319,  319,  319,  319,  319,  319,  320,  320,  320,
      320,  320,  320,  321,  321,  321,  321,  321,  321,  322,
      322,  322,  322,  322,  322,  323,  323,  323,  323,  323,
      323,  324,  324,  324,  324,  324,  324,  325,  325,  325,
      325,  325,  325,  326,  326,  326,  326,  326,  326,  327,
      327,    0,  327,  328,  328,  328,  328,  328,  328,  329,
      329,  329,  329,  329,  329,  330,  330,  330,  330,  330,

      330,  331,  331,  331,  331,  331,  331,  332,  332,  332,
      332,  332,  332,  333,  333,  333,  333,  333,  333,  335,
      335,  335,  335,  335,  336,  336,  336,  336,  336,  336,
      337,  337,  337,  337,  337,  337,  338,  338,  338,  338,
      338,  338,  339,  339,  339,  339,  341,  341,  341,  341,
      341,  342,    0,  342,  342,  343,    0,  343,  344,  344,
      344,  344,  344,  345,  345,  345,  345,  345,  346,  346,
      346,  346,  346,  347,  347,  347,  347,  347,  348,  348,
      348,  348,  348,  348,  349,  349,  349,  349,  349,  349,
      350,  350,  350,  350,  350,  350,  351,  351,  351,  351,

      351,  351,  352,  352,  352,  352,  352,  352,  353,  353,
      353,  353,  353,  353,  354,  354,  354,  354,  354,  354,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "markdown.grammar"
#line 903 "lex.markdown.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    yy_size_t yy_n_chars;
    yy_size_t yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

int markdownlex_init (yyscan_t* scanner);

int markdownlex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int markdownlex_destroy (yyscan_t yyscanner );

int markdownget_debug (yyscan_t yyscanner );

void markdownset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE markdownget_extra (yyscan_t yyscanner );

void markdownset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *markdownget_in (yyscan_t yyscanner );

void markdownset_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *markdownget_out (yyscan_t yyscanner );

void markdownset_out  (FILE * out_str ,yyscan_t yyscanner );

yy_size_t markdownget_leng (yyscan_t yyscanner );

char *markdownget_text (yyscan_t yyscanner );

int markdownget_lineno (yyscan_t yyscanner );

void markdownset_lineno (int line_number ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int markdownwrap (yyscan_t yyscanner );
#else
extern int markdownwrap (yyscan_t yyscanner );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int markdownlex (yyscan_t yyscanner);

#define YY_DECL int markdownlex (yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 38 "markdown.grammar"


#line 1128 "lex.markdown.c"

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			markdownensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				markdown_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		markdown_load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 311 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1621 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 40 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNEM, yyscanner);}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 41 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNSTRONG, yyscanner);}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 42 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNSTRONGEM, yyscanner);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 43 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNSTRIKETHROUGH, yyscanner);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 44 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNCODESPAN, yyscanner);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 45 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNHEADER, yyscanner);}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 46 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNMULTILINEHEADER, yyscanner);}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 47 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNURL, yyscanner);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 48 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNHREF, yyscanner);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 49 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNBULLETSTART, yyscanner);}
	YY_BREAK
case 11:
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 51 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNNEWLINE, yyscanner);}
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 52 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNPARAGRAPH, yyscanner);}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 53 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNUNKNOWN, yyscanner);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 54 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNUNKNOWN, yyscanner);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 56 "markdown.grammar"
ECHO;
	YY_BREAK
#line 1297 "lex.markdown.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * markdownlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( markdownwrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of markdownlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					markdownrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			markdownrestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) markdownrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 311 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 311 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 310);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yy_size_t offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					markdownrestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( markdownwrap(yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void markdownrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        markdownensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            markdown_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	markdown_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	markdown_load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void markdown_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		markdownpop_buffer_state();
	 *		markdownpush_buffer_state(new_buffer);
     */
	markdownensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	markdown_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (markdownwrap()) processing, but the only time this flag
	 * is looked at is after markdownwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void markdown_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE markdown_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) markdownalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in markdown_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) markdownalloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in markdown_create_buffer()" );

	b->yy_is_our_buffer = 1;

	markdown_init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with markdown_create_buffer()
 * @param yyscanner The scanner object.
 */
    void markdown_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		markdownfree((void *) b->yy_ch_buf ,yyscanner );

	markdownfree((void *) b ,yyscanner );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a markdownrestart() or at EOF.
 */
    static void markdown_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	markdown_flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then markdown_init_buffer was _probably_
     * called from markdownrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void markdown_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		markdown_load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void markdownpush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	markdownensure_buffer_stack(yyscanner);

	/* This block is copied from markdown_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from markdown_switch_to_buffer. */
	markdown_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void markdownpop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	markdown_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		markdown_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void markdownensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)markdownalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in markdownensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)markdownrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in markdownensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE markdown_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) markdownalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in markdown_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	markdown_switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to markdownlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       markdown_scan_bytes() instead.
 */
YY_BUFFER_STATE markdown_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return markdown_scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to markdownlex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE markdown_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) markdownalloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in markdown_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = markdown_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in markdown_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE markdownget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int markdownget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int markdownget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *markdownget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *markdownget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
yy_size_t markdownget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *markdownget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void markdownset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void markdownset_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "markdownset_lineno called with no buffer" , yyscanner); 
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void markdownset_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "markdownset_column called with no buffer" , yyscanner); 
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see markdown_switch_to_buffer
 */
void markdownset_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void markdownset_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int markdownget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void markdownset_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* markdownlex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int markdownlex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) markdownalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* markdownlex_init_extra has the same functionality as markdownlex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to markdownalloc in
 * the yyextra field.
 */

int markdownlex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    markdownset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) markdownalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    markdownset_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from markdownlex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * markdownlex_init()
     */
    return 0;
}

/* markdownlex_destroy is for both reentrant and non-reentrant scanners. */
int markdownlex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		markdown_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		markdownpop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	markdownfree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        markdownfree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * markdownlex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    markdownfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *markdownalloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *markdownrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void markdownfree (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see markdownrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 56 "markdown.grammar"



int markdownwrap(yyscan_t yyscanner){return 1;}

